app/poker/__init__.py
from .card import Card
from .deck import Deck
from .player import Player
from .action import Action
from .round import Round
from .pot import Pot
from .hand import Hand
from .session import Session

app/poker/table/__init__.py
from .table import Table
from .circularlinkedlist import CircularLinkedList

app/replayer/__init__.py
from flask import Blueprint, request, jsonify, session, render_template, current_app, redirect
from app.utils.models import get_db_connection, load_hands_from_db
from app.utils.hand_parser import get_data_for_replayer
from werkzeug.utils import secure_filename
from app.utils.decorators import login_required
import time
import json
import os

replayer_bp = Blueprint('replayer', __name__)


def get_hands_count(db_path, q = None):
    with get_db_connection(db_path) as conn:
        cursor = conn.cursor()
        query = f"""
        SELECT COUNT(id) AS count
        FROM hands
        """
        if q is not None:
            query += f"WHERE players GLOB '*{q}*' OR table_name GLOB '*{q}*' OR hero_hand_class GLOB '*{q}*'"
        cursor.execute(query)
        count = cursor.fetchone()["count"]
    return count 

def get_hands_list(db_path, page = 1, q = None, return_count = True):
    # q is the search filter

    limit = 50                              # Default items per page
    offset = (page - 1) * limit             # Calculate offset
    with get_db_connection(db_path) as conn:
        cursor = conn.cursor()
        query = f"""
        SELECT id,
        table_name,
        date_time,
        hero_cards AS cards,
        hero_position AS position,
        hero_profit AS profit,
        players
        FROM hands
        """
        if q is not None:
            query += f"WHERE players GLOB '*{q}*' OR table_name GLOB '*{q}*' OR hero_hand_class GLOB '*{q}*'"
        query += f"ORDER BY date_time DESC LIMIT {limit} OFFSET {offset}"
        cursor.execute(query)
        results = cursor.fetchall()

    if return_count:
        count = get_hands_count(db_path, q)
        return results, count

    return results

@replayer_bp.route('/')
@login_required
def replayer():
    db_path = session.get("db_path", None)
    session["page"] = 1
    session["filter"] = None
    hands_list, count = get_hands_list(db_path, session["page"])
    return render_template('replayer_page.html', hands_list = hands_list, total_count = count)


@replayer_bp.route("/search")
def search():
    db_path = session.get("db_path", None)
    search_filter = request.args.get("filter")
    session["filter"] = search_filter
    session["page"] = 1
    hands_list, count = get_hands_list(db_path, 1, search_filter) 
    return render_template("hands_table.html", hands_list=hands_list, total_count = count)


@replayer_bp.route("/load_next_page")
def load_next_page():
    db_path = session.get("db_path", None)
    page = session["page"] +1
    session["page"] = page
    hands_list = get_hands_list(db_path, page, session.get("filter", None), return_count = False) 
    return render_template("hands_list.html", hands_list=hands_list)

@replayer_bp.route('/select_hand')
def select_hand():
    selected_index = request.args.get('selected_hand')

    # Retrieve the full ohh_data from the database for the selected hand
    with get_db_connection(session["db_path"]) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT ohh_data FROM hands WHERE id=?", (selected_index,))
        result = cursor.fetchone()
        if not result:
            return jsonify({"error": "Invalid hand selection"}), 400
        
        # Load ohh_data and parse it
        ohh_data = json.loads(result["ohh_data"])
        general_data, game_states = get_data_for_replayer(ohh_data)

    session["general_data"] = general_data
    session["game_states"] = game_states
    session["current_state"] = 0 # Change here the default loaded state

    return render_template("hand_replayer.html", general_data=general_data, gamestate=game_states[session["current_state"]]) 

@replayer_bp.route("/beginning")
def beginning():
    session["current_state"] = 0
    return render_template("hand_replayer.html",
                           general_data=session["general_data"],
                           gamestate=session["game_states"][0])

@replayer_bp.route("/previous")
def previous():
    if session["current_state"] > 0 :
        session["current_state"] -= 1
    return render_template("hand_replayer.html",
                           general_data=session["general_data"],
                           gamestate=session["game_states"][session["current_state"]])


@replayer_bp.route("/next")
def next():
    if session["current_state"] < len(session["game_states"]) -1 :
        session["current_state"] += 1
    return render_template("hand_replayer.html",
                           general_data=session["general_data"],
                           gamestate=session["game_states"][session["current_state"]])

@replayer_bp.route("/end")
def end():
    session["current_state"] = len(session["general_data"]) -1
    return render_template("hand_replayer.html",
                           general_data=session["general_data"],
                           gamestate=session["game_states"][-1])

app/rooms/__init__.py
from flask import Blueprint

rooms_bp = Blueprint("rooms", __name__)

from .controllers import *

app/rooms/controllers.py
from flask import  request, render_template, session, flash
from decimal import Decimal
from app.ws import sock
from .models import create_room, get_all_rooms, get_room, delete_room_by_id
from app.utils.decorators import login_required, htmx_required
from app.utils.wrappers import render_template_flash, render_flash
from app.utils.scripts import open_window_script
import numpy as np
import random
from app.poker.table import Table
import json

from . import rooms_bp

# Track all active WebSocket connections to broadcast updates
connected_sockets = set()
tables_dict = {}

# Fixed global variab
# Index route for now
@rooms_bp.route("/", methods=["GET"])
def rooms():
    """
    Returns an HTML snippet listing all rooms (rooms_list.html).
    """
    redirect_message = session.pop('redirect_message', None)  # Get and remove the message
    login_popup = redirect_message == 'need_to_login' 

    rooms = get_all_rooms(tables_dict)
    return render_template("rooms.html", rooms=rooms, login_popup=login_popup)

@rooms_bp.route("/create", methods=["GET", "POST"])
@login_required
@htmx_required
def create():
    """
    Creates a new room, broadcasts the update to all WebSocket clients,
    and returns the updated rooms list for immediate HTMX swap.
    """
    if request.method == "POST":
        room_name = request.form.get("name", "").strip()
        max_players = int(request.form.get("max_players", "").strip())
        stakes = request.form.get("stakes", "").strip()
        if room_name and max_players and stakes:
            try:
                # Split stakes into small blind and big blind
                small_blind, big_blind = map(float, stakes.split('/'))
                room_id = create_room(room_name, max_players, small_blind, big_blind)
            except Exception as e:
                print(e)
                flash(f"Error creating room : {str(e)}", "error")
            else: # If there is no error
                broadcast_room_update()
                flash("Room created successfully.", "success")
                return render_template('flash_messages.html') 
        else:
            flash("All fields are required and max players must be a number.", "error")
            
        return render_template_flash('room_creation.html') # If there is an error

    return render_template_flash("room_creation.html") # If the request is a GET request


@rooms_bp.route('/room/<int:room_id>')
@login_required
def poker_room(room_id):
    player_id = session["user_id"]
    room_db = get_room(room_id)
    table = tables_dict.get(room_id, None)

    if table is None:
        table = Table(table_id=room_id,
                      table_name=room_db["name"],
                      small_blind=Decimal(str(room_db["small_blind"])),
                      big_blind=Decimal(str(room_db["big_blind"])),
                      table_size=room_db["max_players"])
        tables_dict[room_id] = table

    # Check if player in already in the room dictionnary
    if table.players.get(player_id, None) is None: # If player is not in the room 
        try:
            player = table.new_player(id = player_id, name = session["username"], starting_stack = 100*table.big_blind)
        except Exception as e:
            print(e)
            return f"{e}"

    broadcast_room_update()
    broadcast_table_update(room_id)

    general_data, gamestate = table.get_display_data(player_id)

    return render_template("poker.html", general_data = general_data, gamestate = gamestate)


@rooms_bp.route('/start/<int:room_id>', methods=["GET", "POST"])
@login_required
def start_game(room_id):
    table = tables_dict.get(room_id)
    if not table:
        print("Room not found")
        return 'Game not found'

    try:
        table.start_new_game()
    except Exception as e:
        flash(f"{e}", "error")
        return render_template("flash_messages.html")
    
    broadcast_table_update(room_id)
    return  '', 204

@rooms_bp.route('/delete/<int:room_id>', methods=["GET"])
@login_required
def delete_room(room_id):
    try:
        delete_room_by_id(tables_dict, room_id)
        broadcast_room_update()
    except Exception as e:
        flash(f"{e}","error")
        return render_flash()

    # We need to return a signal to delete the current window
    return "<script> window.close() </script>"

# Quit room
@rooms_bp.route('/quit/<int:room_id>', methods=["GET"])
def quit_room(room_id):
    player_id = session["user_id"]
    table = tables_dict.get(room_id, None)
    if table is None:
        flash("Room not found", "error")
        return render_flash()
    player = table.players.get(player_id, None)
    if player is None:
        flash("Player not found", "error")
        return render_flash()
    active_players = table.active_players.to_list()
    for player in active_players:
        if player.id == player_id:
            flash(f"Finish the current game before leaving","error")
            return render_flash()

    table.remove_player(player_id)
    broadcast_room_update()
    broadcast_table_update(room_id)
    return "<script> window.close() </script>"


# Route for opening a new window for the given room_id
@rooms_bp.route('/load_room/<int:room_id>')                
@login_required
def load_room(room_id):
    return open_window_script(f"/room/{room_id}", 1000, 1000)


@rooms_bp.route('/action/<int:room_id>/<action>', methods=['POST'])
@login_required
def player_action(room_id, action):
    amount = Decimal(request.headers.get("HX-Prompt",0))
    table = tables_dict.get(room_id)
    if table.is_player_turn(session["user_id"]):
        try:
            table.action(action_type = action, amount=amount*table.big_blind)
        except Exception as e:
            print(f" {e}")
            flash(f"{e}", "error")
            return render_flash()
        broadcast_table_update(room_id)
    else:
        flash("You can't take action right now")
        return render_flash()
    return '', 204


@sock.route("/rooms_ws")
def rooms_ws(ws):
    """
    A pure WebSocket endpoint for broadcasting changes to all connected clients.
    We don't necessarily need to receive data from the client,
    but we keep this loop open so the connection remains alive.
    """
    connected_sockets.add(ws)
    print("Rooms WebSocket connected", ws) 
    try:
        while True:
            msg = ws.receive()
            if msg is None:
                # Client disconnected
                break
    finally:
        print("Rooms WebSocket disconnected", ws) 
        connected_sockets.discard(ws)

@sock.route("/table_ws/<int:room_id>")
def table_ws(ws, room_id):
    # Add socket to player in tables_dict
    print(session["username"],": Table WebSocket connected", ws) 

    # Check if room is in tables_dict
    table = tables_dict.get(room_id, None)
    if table is None:
        ws.close()
        return

    # Check if player is in the room
    player = table.players.get(session["user_id"], None)
    if player is None:
        ws.close()
        return 

    player.socket = ws
    player.status = "Active"

    try:
        while True:
            msg = ws.receive()
            if msg is None:
                # Client disconnected
                break
    except Exception as e:
        print(f" {e}")
    finally:
        print(session["username"],": Table WebSocket disconnected", ws) 
        player.status = "disconnected"

def broadcast_room_update():
    """
    Gets the updated rooms list and sends it to every connected WebSocket client.
    We'll leverage HTMX's WebSocket extension so no custom JS is needed.
    """
    print("Rooms updated. Broadcasting to all clients.")
    rooms = get_all_rooms(tables_dict)
    # Render a fresh snippet of the rooms list
    html = render_template("_rooms.html", rooms=rooms)

    for sock_conn in list(connected_sockets):
        try:
            sock_conn.send(html)
        except:
            connected_sockets.discard(sock_conn)

def broadcast_table_update(room_id):
    table = tables_dict[room_id]
    for pp_id, pp in table.players.items():
        if pp.socket is not None:
            general_data, gamestate = table.get_display_data(pp_id)
            html = render_template("poker_table_obb.html", general_data=general_data, gamestate = gamestate)
            try :
                pp.socket.send(html)
            except:
                print("The connection should have been deleted from the dict")
                tables_dict[room_id].players[session["user_id"]].socket = None

app/statistics/__init__.py
from flask import Blueprint, request, jsonify, session, render_template, current_app, redirect, send_file
from app.utils.models import *
from app.utils.plots import *
from collections import defaultdict
from app.utils.decorators import login_required

import json

statistics_bp = Blueprint('statistics', __name__)

@statistics_bp.route('/')
@login_required
def statistics():
    db_path = session.get("db_path", None)

    # Update and retrieve overall statistics
    update_players_statistics(session["db_path"])
    players = get_players_list(session["db_path"])
    
    # Get selected player from query parameters
    selected_player = request.args.get('selected_player', None)

    player_stats = None
    position_stats = None
    player_stats_short = None
    position_stats_short = None

    if selected_player :
        position_stats = get_player_statistics_per_position(db_path, selected_player, min_players = 4)
        position_stats_short = get_player_statistics_per_position(db_path, selected_player, max_players = 3)
        player_stats = get_player_full_statistics(db_path, selected_player, min_players = 4)
        player_stats_short = get_player_full_statistics(db_path, selected_player, max_players = 3)

    # if selected_player is None: selected_player = stats[0]["name"] # By default select the player with the greater number of hands

    return render_template('statistics.html',
                           players = players,
                           selected_player=selected_player,
                           player_stats = player_stats,
                           position_stats = position_stats,
                           player_stats_short = player_stats_short,
                           position_stats_short = position_stats_short,
                           )

@statistics_bp.route('/player_stats_plot')
def player_stats_plot():
    db_path = session.get("db_path")
    player_name = request.args.get('name')
    window_size = int(request.args.get('window_size', 10))  # Default window size to 10 if not provided
    if not db_path or not player_name:
        return jsonify({"error": "Database path or player name missing"}), 400

    img = generate_cummulative_profit_plot(player_name, db_path, window_size)
    return send_file(img, mimetype="image/png")

@statistics_bp.route('/player_opening_range_plot')
def player_opening_range_plot():
    db_path = session.get("db_path")
    player_name = request.args.get('name')
    if not player_name:
        return jsonify({"error": "Player name missing"}), 400
    img = generate_opening_range_plot(player_name, db_path)
    return send_file(img, mimetype="image/png")

app/templates/_rooms.html
<!-- A simple partial that displays all rooms in a <ul> -->
<div id="rooms_list" hx-swap-obb="innerHTML">
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Stakes</th>
        <th>Players</th>
      </tr>
    </thead>
    <tbody>
      {% for room in rooms %}
      <tr class="clickable-row"
        hx-get='/load_room/{{ room.id }}', hx-target="#popup">
        <td>{{ room.id }}</td>
        <td>{{ room.name }}</td>
        <td>{{ room.small_blind }} / {{ room.big_blind}}</td>
        <td>{{ room.players}} / {{ room.max_players }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            Nabla Poker
            - {% block subtitle %}{% endblock %}
        </title>
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
        <script src="https://unpkg.com/htmx.org@1.9.12"></script>
        <script src="https://unpkg.com/htmx.org@1.9.12/dist/ext/ws.js"></script>
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    </head>
    <body>
        <header>
            <div id="pages" class="menu">
                <a href="/">
                    Home
                </a>
                <a href="{{ url_for('replayer.replayer') }}">
                    Hand Replayer 
                </a>
                <a href="{{ url_for('statistics.statistics') }}">
                    Statistics
                </a>
            </div>
            <div id="log_status" class="menu" style="margin-left:auto;">
                {% if session.user_id %}
                <p> Logged in as <b>{{ session.username }}</b></p>
                <a hx-get="{{ url_for('auth.logout') }}">Logout</a>
                {% else %}
                <a hx-get="{{ url_for('auth.login') }}" hx-target="#popup">Login</a>
                <a hx-get="{{ url_for('auth.register') }}" hx-target="#popup">Register</a>
                {% endif %}
            </div>
        </header>
        <main  class="main-content">


            {% block content %}{% endblock %}

            <div id=popup>
                {% if login_popup %}
                {% include 'login.html' %}
                {% endif %}
            </div>

            {% include 'flash_messages.html' %}

        </main>
        <footer>
            <p>&copy; 2024 Nabla Poker</p>
        </footer>

        <script src="{{ url_for('static', filename='js/table_navigation.js') }}"></script>
    </body>
</html>

app/templates/flash_messages.html
<div id="flash_container" hx-swap-oob="innerHTML">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="flash_message {{category}}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>

app/templates/hand_replayer.html
<div class="box">
    {% include "poker_table.html" %}
    
    <div id="navigation-buttons-container">
        <button 
            hx-get="/replayer/beginning" hx-trigger="click" hx-target="#hand-replayer-container">
            Beginning
        </button>
        <button id="previous-button"
            hx-get="/replayer/previous" hx-trigger="click" hx-target="#hand-replayer-container">
            Previous
        </button>
        <button id="next-button"
            hx-get="/replayer/next" hx-trigger="click" hx-target="#hand-replayer-container">
            Next
        </button>
        <button 
            hx-get="/replayer/end" hx-trigger="click" hx-target="#hand-replayer-container">
            End
        </button>
    </div>
</div>

{% if gamestate.final_pots %} 
<div class="box">
    <h3>Final Pot(s)</h3>

    {% for pot in gamestate.final_pots %}
    <div>Total Pot: {{pot.amount}} | Rake: {{pot.rake}}</div>
    <table class="pot-table" style="width:50%;">
        <thead>
            <tr>
                <th>Winner</th>
                <th>Win Amount</th>
                <th>Rake</th>
                <th>Cashout Fee</th>
                <th>Cashout Amount</th>
            </tr>
        </thead>
        <tbody id="potWinnersTable"></tbody>
        {% for win in pot.player_wins %}
        <td>{{win.name}}</td>
        <td>{{win.win_amount}}</td>
        <td>{{win.contributed_rake}}</td>
        <td>{{win.cashout_fee}}</td>
        <td>{{win.cashout_amount}}</td>
        {% endfor %}
    </table>
    {% endfor %}
</div>
{% endif %} 

app/templates/hands_list.html
{% for hand in hands_list %}
<tr class="clickable-row"
    hx-get="/replayer/select_hand?selected_hand={{hand.id}}" hx-trigger="click" hx-target="#hand-replayer-container">
    <td>{{ hand.cards}}</td>
    <td>{{ hand.date_time }}</td>
    <td>{{ hand.table_name}}</td>
    <td>{{ hand.profit}}</td>
</tr>
{% endfor %}

app/templates/index.html
{% extends "base.html" %}

{% block subtitle %}Home{% endblock %}

{% block content %}
<h2>Flask-Sock Demo with HTMX</h2>

<div class="box">
    <p>Type a message and press Enter. Type <b>close</b> to end the connection.</p>

    <div hx-ext="ws" ws-connect="/echo" style="margin: 10px;">
        <form ws-send="submit">
            <input type="text" name="message" placeholder="Enter your message">
        </form>
        {% include '_messages.html' %}
    </div>
</div>
<style>
.messages{
    display: flex;
    flex-direction: rows;
} 
.message{
    margin: 5px;
}
</style>
{% endblock %}

app/templates/player_statistics.html
<div class="box">
    <!-- Slider to control rolling window size -->
    <h3>Player Statistics</h3>
    <!-- Player Plot Display -->
    {% if selected_player %}
    <div>
        <img id="playerChart" src="{{ url_for('statistics.player_stats_plot', name=selected_player) }}" style="max-width: 100%; height: auto;">
    </div>

    <label for="windowSizeSlider" id="sliderLabel">
        Rolling mean window size:
        <input type="range" id="windowSizeSlider" min="5" max="100" value="10" step ="5" oninput="updatePlot()" />
        <span id="windowSizeValue">10</span>  <!-- Display slider value -->
    </label>
    {% else %}
    <div style="margin:10px">Select a player to view their statistics.</div>
    {% endif %}
</div>

<div class="box">
    <h3> Player Statistics per Position (for 4 to 6 players) </h3>
    {% if selected_player %}
    <table style="width: 80%; border-collapse: collapse ; top-margin: 2px; ">
        <thead style="position: sticky; top: 0; z-index: 1;">
            <tr>
                <th>Position</th>
                <th>Hands</th>
                <th>VPIP (%)</th>
                <th>PFR (%)</th>
                <th>AF</th>
                <th>2bet (%)</th>
                <th>limp (%)</th>
                <th>3bet (%)</th>
                <th>Win rate (bb/hand)</th>
            </tr>
        </thead>
        <tbody>
            {% for p in position_stats %}
            <tr>
                <td>{{ p.position}}</td>
                <td>{{ p.hands }}</td>
                <td>{{ p.VPIP}}</td>
                <td>{{ p.PFR}}</td>
                <td>{{ p.AF}}</td>
                <td>{{ p.two_bet}}</td>
                <td>{{ p.limp}}</td>
                <td>{{ p.three_bet}}</td>
                <td>{{ p.bb_per_hand }}</td>
            </tr>
            {% endfor %}

            <tr>
                <td> Overall </td>
                <td>{{ player_stats.hands }}</td>
                <td>{{ player_stats.VPIP}}</td>
                <td>{{ player_stats.PFR}}</td>
                <td>{{ player_stats.AF}}</td>
                <td>{{ player_stats.two_bet}}</td>
                <td>{{ player_stats.limp}}</td>
                <td>{{ player_stats.three_bet}}</td>
                <td>{{ player_stats.bb_per_hand }}</td>
            </tr>
        </tbody>
    </table>
    {% else %}
    <div style="margin:10px">Select a player to view their statistics.</div>
    {% endif %}
</div>

<div class="box">
    <h3> Player Statistics per Position (2 or 3 players) </h3>
    {% if selected_player %}
    <table style="width: 80%; border-collapse: collapse ; top-margin: 2px; ">
        <thead style="position: sticky; top: 0; z-index: 1;">
            <tr>
                <th>Position</th>
                <th>Hands</th>
                <th>VPIP (%)</th>
                <th>PFR (%)</th>
                <th>AF</th>
                <th>2bet (%)</th>
                <th>limp (%)</th>
                <th>3bet (%)</th>
                <th>Win rate (bb/hand)</th>
            </tr>
        </thead>
        <tbody>
            {% for p in position_stats_short %}
            <tr>
                <td>{{ p.position}}</td>
                <td>{{ p.hands }}</td>
                <td>{{ p.VPIP}}</td>
                <td>{{ p.PFR}}</td>
                <td>{{ p.AF}}</td>
                <td>{{ p.two_bet}}</td>
                <td>{{ p.limp}}</td>
                <td>{{ p.three_bet}}</td>
                <td>{{ p.bb_per_hand }}</td>
            </tr>
            {% endfor %}

            <tr>
                <td> Overall </td>
                <td>{{ player_stats_short.hands }}</td>
                <td>{{ player_stats_short.VPIP}}</td>
                <td>{{ player_stats_short.PFR}}</td>
                <td>{{ player_stats_short.AF}}</td>
                <td>{{ player_stats_short.two_bet}}</td>
                <td>{{ player_stats_short.limp}}</td>
                <td>{{ player_stats_short.three_bet}}</td>
                <td>{{ player_stats_short.bb_per_hand }}</td>
            </tr>
        </tbody>
    </table>
    {% else %}
    <div style="margin:10px">Select a player to view their statistics.</div>
    {% endif %}
</div>

<div class="box" >
    <h3>Player Opening Range </h3>
    <!-- Player Plot Display -->
    {% if selected_player %}
    <div>
        <img id="playerOpeningRange" src="{{url_for('statistics.player_opening_range_plot', name=selected_player) }}" style="max-width: 100%; height: auto;">
    </div>
    {% else %}
    <div style="margin:10px">Select a player to view their opening range.</div>
    {% endif %}
</div>

<style>
/* Center the content inside the label */
#sliderLabel {
    display: flex;
    align-items: center; /* Center text and slider vertically */
    gap: 15px;           /* Add space between the text, slider, and displayed value */
    margin-top: 20px;    /* Add top margin for spacing */
    justify-content: center; /* Center-align everything inside label */
}
</style>


<script>
// JavaScript to handle slider changes and update the plot dynamically
function updatePlot() {
    const playerName = "{{selected_player}}";  // Player name passed from the server
    const windowSize = document.getElementById("windowSizeSlider").value;
    document.getElementById("windowSizeValue").textContent = windowSize;  // Update displayed slider value

    // Update plot image by changing the 'src' attribute with new window size
    document.getElementById("playerChart").src = `/statistics/player_stats_plot?name=${playerName}&window_size=${windowSize}`;
}
</script>

app/templates/room_creation.html
<div id="popup" class="popup">
  <div class="box" style="position:relative;">
    <h3>Room Creation</h3>

    <form class="loginForm" hx-post="{{ url_for('rooms.create') }}" hx-target="#popup">
      <div>
        <label for="name">Room Name:</label>
        <input type="text" id="name" name="name" required />
      </div>

      <div>
        <label for="max_players">Max Players:</label>
        <select id="max_players" name="max_players" required>
          <option value="2">2</option>
          <option value="6">6</option>
          <option value="9">9</option>
        </select>
      </div>

      <div>
        <label for="game_type">Game Type:</label>
        <select id="stakes" name="stakes" required>
          <option value="0.01/0.02">0.01/0.02</option>
          <option value="0.02/0.04">0.02/0.04</option>
          <option value="0.05/0.10">0.05/0.10</option>
          <option value="0.10/0.20">0.10/0.20</option>
          <option value="0.25/0.50">0.25/0.50</option>
          <option value="0.50/1.00">0.50/1.00</option>
          <!-- Add more options as needed -->
        </select>
      </div>

      <button type="submit">Create Room</button>

      <a id="exit-button" hx-get="/exit_popup" hx-target="#popup" hx-trigger="click, keyup[key=='Escape'] from:body">x</a>

    </form>
  </div>
</div>

app/templates/rooms.html
{% extends "base.html" %}

{% block subtitle %}Rooms{% endblock %}

{% block content %}
<div class="box">
    <h3>Rooms</h3>

    <button hx-get="{{ url_for('rooms.create') }}" hx-target="#popup">
        Create Room
    </button>

    <div hx-ext="ws" ws-connect="/rooms_ws" style="margin: 10px;">
            {% include '_rooms.html' %}
    </div>
</div>

{% endblock %}

app/templates/statistics.html
{% extends "base.html" %}

{% block subtitle %}Statistics{% endblock %}

{% block content %}
<h2>Statistics</h2>

<div class="main-container">
    <div id="tableContainer" class="box" style="flex: 1;">
        <table style="width: 100%; border-collapse: collapse ; table-layout : fixed;  margin: 0; ">
            <thead style="position: sticky; top: 0; z-index: 1;">
                <tr>
                    <th>Name</th>
                    <th>Hands</th>
                    <th>VPIP(%)</th>
                    <th>PFR(%)</th>
                </tr>
            </thead>
        </table>
        <div style = "width: 100%; overflow-y: auto; max-height: 1500px;">
            <table style="width: 100%; border-collapse: collapse ; table-layout : fixed;  margin: 0; ">
                <tbody>
                    {% for player in players%}
                    <tr class="clickable-row" onclick="location.href='{{ url_for('statistics.statistics', selected_player=player.name) }}'">
                        <td>{{ player.name }}</td>
                        <td>{{ player.hands }}</td>
                        <td>{{ player.vpip }}</td>
                        <td>{{ player.pfr }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div id="player_statistics" style="flex: 2;">
        {% include "player_statistics.html" %}
    </div>
</div>


{% endblock %}